# 配置语言及相应版本
language: node_js
node_js:
- '8'

# 项目所在分支
branches:
  only:
  - master
  
# 配置环境
before_install:
# 替换为刚才生成的解密信息
- openssl aes-256-cbc -K $encrypted_99a02cfc8694_key -iv $encrypted_99a02cfc8694_iv
  -in .travis/ci_rsa.enc -out ~/.ssh/ci_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/ci_rsa
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/ci_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'emptychan'
- git config --global user.email chen19941018@live.com
# 将 GitHub Token 替换到 next.yml 中
- sed -i "s/CJH_TOKEN/${CJH_TOKEN}/" _config.yml
# 安装依赖
install:
- npm install hexo-cli -g
- npm install
# 部署的命令
script:
- npm run deploy # hexo clean && hexo g -d

cache:
  directories:
  - node_modules
